---
title: "Microarray with RMA"
author: "Alquama"
date: "2023-10-22"
output: html_document
---

```{r setup, include=FALSE}

```

## Load the approprate libraies##
```{r}
library(tidyr)
library(GEOquery)
library(affy)
library(dplyr)
library(tibble)
```


### Retrived the supplementary files from the NCBI GEO with the accession number##
```{r}
getGEOSuppFiles("GSE148537")
untar("GSE148537/GSE148537_RAW.tar", exdir = 'microarray data/')
# reading in .cel files
raw.data <- ReadAffy(celfile.path = "microarray data/")
```

### Perfrom RMA normalization ###
```{r}
# performing RMA normalization
normalized.data <- rma(raw.data)

# get expression estimates
normalized.expr <- as.data.frame(exprs(normalized.data))

# map probe IDs to gene symbols
gse <- getGEO("GSE148537", GSEMatrix = TRUE)

# fetch feature data to get ID - gene symbol mapping
feature.data <- gse$GSE148537_series_matrix.txt.gz@featureData@data
# subset
feature.data <- feature.data[,c(1,11)]

normalized.expr <- normalized.expr %>%
  rownames_to_column(var = 'ID') %>%
  inner_join(., feature.data, by = 'ID')
```